### ISSUE TITLE
How to analyze BERT results

### ISSUE THREAD

**Issue by Bachstelze** [aaronmueller/clams#2]
Can we use the `analyze_results.py` script also for txt results from `eval_bert.py`? Or do we have to convert them somehow to `.wordscores` files?

**Comment by aaronmueller** [comment]
To get accuracies for BERT, you can use `bert-syntax/gen_marvin_tbl.py`. I'll add this clarification to the README, and when I get some time I'll also refactor this to take command-line arguments. Thanks!
