### ISSUE TITLE
German case in prep_anim

### ISSUE THREAD

**Issue by namednil** [aaronmueller/clams#3]
Thanks for this great dataset! I've noticed an issue in `prep_anim.txt` for German: sentences that are supposed to be grammatical are ungrammatical (and the corresponding ungrammatical sentences are ungrammatical in an additional way). Example:

```
True	die Schriftsteller vor den Wächter sind alt
False	die Schriftsteller vor den Wächter ist alt
```
Here,  `vor` requires dative but `Wächter` isn't a dative form. Instead, it should be

```
True	die Schriftsteller vor den Wächtern sind alt
False	die Schriftsteller vor den Wächtern ist alt
```

As far as I can see this issue only affects those instances that use `Köche, Taxifahrer, Wächter` whose dative forms are `Köchen, Taxifahrern, Wächtern` respectively. In other words, instances that use `Vätern, Leitern, Mitarbeitern, Ministern, Tänzern` are fine.

**Comment by aaronmueller** [comment]
Thank you very much for pointing this out! Just pushed a fix for those three dative plurals.
